SELECT * FROM shopping.addresses;

INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (1, 3, '189 Hodge Stravenue Suite 904', 'Lake Deborahville', 'Vermont', '91980', 'Zambia');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (2, 14, '620 Alexis Key', 'New Michaelfurt', 'Alaska', '83947', 'Holy See (Vatican City State)');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (3, 48, '5647 Contreras Wall', 'Port Barbara', 'New Mexico', '87478', 'Northern Mariana Islands');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (4, 24, '97141 Smith Vista Suite 413', 'Jamesland', 'Virginia', '53811', 'Philippines');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (5, 29, '21833 Henry Springs Apt. 330', 'South Roger', 'Washington', '77817', 'Antarctica (the territory South of 60 deg S)');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (6, 33, '50518 Nicholas Cove Apt. 171', 'South Beverly', 'Montana', '34379', 'Bermuda');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (7, 41, '86122 Farley Locks', 'Richardsonton', 'New Jersey', '44599', 'Iceland');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (8, 34, '094 Sandra Forks', 'East Gregory', 'Alaska', '21220', 'Wallis and Futuna');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (9, 24, '443 Morgan Manor', 'Kristinaborough', 'Ohio', '20811', 'New Caledonia');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (10, 34, '659 Nicole Route', 'Michaelberg', 'Rhode Island', '20730', 'United Arab Emirates');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (11, 14, '427 Beck Haven Apt. 519', 'West Aaronbury', 'Delaware', '69668', 'Finland');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (12, 13, '1721 Williams Village', 'South Elizabethfort', 'Missouri', '24410', 'Bahamas');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (13, 42, '52078 Peterson Burg Suite 788', 'Lake Mary', 'Indiana', '20005', 'Jordan');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (14, 20, '4233 Stanton Corner', 'North Sheilamouth', 'Nevada', '96360', 'Cocos (Keeling) Islands');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (15, 1, '4154 James Shoals Apt. 898', 'Stewartville', 'Virginia', '72449', 'Cameroon');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (16, 30, '6000 Garcia Ports', 'Adamburgh', 'Wisconsin', '01521', 'Bahrain');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (17, 5, '5272 Wright Fields', 'Michaelmouth', 'Nebraska', '30144', 'Sierra Leone');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (18, 6, '04277 Brian Trace', 'East Joshuaside', 'South Dakota', '59359', 'Malaysia');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (19, 10, '820 David Vista', 'West Cheryl', 'New Mexico', '78551', 'Peru');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (20, 10, '506 Cole Ports', 'North Emilyview', 'Kentucky', '36449', 'Israel');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (21, 26, '390 Jason Unions Suite 190', 'Lake Rodneyborough', 'Iowa', '15345', 'French Polynesia');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (22, 5, '93354 Aaron Bridge Suite 477', 'Bryanview', 'West Virginia', '86421', 'Mali');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (23, 26, '21818 Chen Falls', 'West Jerome', 'Arkansas', '92926', 'Saint Vincent and the Grenadines');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (24, 34, '6117 Meyer Spur Suite 975', 'Andersonhaven', 'Utah', '34817', 'United Arab Emirates');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (25, 40, '5702 Thomas Cliffs Apt. 761', 'Lake Dwayne', 'Georgia', '53627', 'Falkland Islands (Malvinas)');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (26, 44, '42295 Christine Flat Apt. 896', 'West Thomasbury', 'Oklahoma', '20775', 'Belize');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (27, 34, '70771 Fitzgerald Ridge Suite 104', 'New Timothy', 'Michigan', '50323', 'Saudi Arabia');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (28, 29, '29139 Trevino Square Suite 265', 'Lake Danafurt', 'South Carolina', '53875', 'Hong Kong');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (29, 23, '74125 Julia Island Suite 220', 'Ingramberg', 'Montana', '59482', 'Barbados');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (30, 18, '2285 Evan Underpass', 'North Sonyaton', 'Arkansas', '06215', 'Lithuania');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (31, 6, '961 Sherri Corner', 'South Maurice', 'Alaska', '60668', 'Madagascar');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (32, 35, '143 Kaiser Radial Suite 506', 'New Gabriel', 'Nebraska', '71744', 'Faroe Islands');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (33, 44, '666 John Station Apt. 733', 'New Lauren', 'Idaho', '86178', 'Zambia');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (34, 14, '1499 Sharp Flats', 'Port Kathleen', 'Texas', '78053', 'Cameroon');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (35, 9, '10280 Jordan Row Apt. 350', 'North Lukemouth', 'South Carolina', '72856', 'Chad');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (36, 11, '823 Romero Falls Apt. 150', 'Schneidershire', 'Texas', '11230', 'Burundi');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (37, 49, '03603 Boyd Track', 'Jonesmouth', 'Montana', '24384', 'Belize');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (38, 17, '0085 Malone Valleys', 'Port Michael', 'West Virginia', '33827', 'Indonesia');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (39, 24, '49850 Manuel Estates', 'Ramirezview', 'North Carolina', '25888', 'Netherlands Antilles');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (40, 15, '01893 Nguyen Cove', 'Lisaton', 'Illinois', '84326', 'Cote d''Ivoire');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (41, 19, '101 Mark Fall Apt. 236', 'Port Frederickborough', 'Virginia', '24453', 'Armenia');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (42, 47, '5019 Omar Dam Suite 779', 'South Ruth', 'Texas', '93219', 'France');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (43, 46, '981 Courtney Turnpike', 'Gonzalezhaven', 'Texas', '63796', 'Yemen');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (44, 2, '855 Fernandez Spring', 'Avilaland', 'Alaska', '36028', 'Netherlands');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (45, 36, '676 Powell Springs Suite 654', 'Kingport', 'Massachusetts', '13791', 'Greenland');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (46, 20, '6622 Lisa Path', 'East Loriland', 'Virginia', '35803', 'Belarus');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (47, 10, '8215 Adams Run', 'Bryanfurt', 'New Mexico', '30291', 'Libyan Arab Jamahiriya');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (48, 39, '844 Tyler Isle Apt. 640', 'West Kayla', 'California', '67722', 'Mauritania');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (49, 8, '721 Carlson Well', 'Paulmouth', 'Louisiana', '71010', 'Saint Vincent and the Grenadines');
INSERT INTO addresses (address_id, user_id, address_line, city, state, postal_code, country) VALUES (50, 40, '45137 Carpenter Falls', 'Priscillaside', 'Virginia', '84291', 'Comoros');
